### ISSUE TITLE
The model is unaware of agent velocity

### ISSUE THREAD

**Issue by pengzhenghao** [rainmaker22/SMART#13]
https://github.com/rainmaker22/SMART/blob/a329361b63082359be56c9bfaa7e76336c19115f/smart/modules/agent_decoder.py#L167

I just find in code above it seems the velocity is never passed into the model. Is my understanding correct?

That's quite interesting to me as we have a GPT-style agent decoder. If the model is unaware of the velocity, in the very first token, the model has to guess the velocity of this agent in order to pick the best action?

**Comment by rainmaker22** [comment]
https://github.com/rainmaker22/SMART/blob/a329361b63082359be56c9bfaa7e76336c19115f/smart/modules/agent_decoder.py#L178C25-L178C40
As shown in the code, we encode the motion_vector_a, which is derived from the relative position between two consecutive steps. This has some overlap with velocity features, which is why we chose to omit velocity. Of course, adding velocity as a feature is also fine.
